print("Приложение, которое выводит в консоль ФИО студента, факультет, курс, группу и email")
fio = input("Введите ФИО: ")
faculty = input("На каком вы факультете: ")
course = input("На каком вы курсе: ")
group = input("Ваша группа: ")
email = input("Ваш email: " )
print("\n" + "Введенные данные: "+ "\n" + "ФИО: " + fio + "\n" + "Факультет: " + faculty + "\n" + "Курс: " + course + "\n" + "Группа: " + group + "\n" + "Email: " + email)